### ISSUE TITLE
Recursion error with large tree during output.

### ISSUE THREAD

**Issue by d-j-e** [neherlab/treetime#120]
Hi Richard,

First, thanks for such a great program/package, especially the ASR feature...

However, I was running 'ancestor' a very large tree (~7800 isolates) with two different roots (one tree being more 'unbalanced' than the other, meaning greater node depth on one sub-branch of the root. This lead to the following error whilst outputting the tree:

```
--- alignment including ancestral nodes saved as  
	 20200422_snppar_root_bat/treetime_out/ancestral_sequences.fasta

2020-05-11_18:31:55.468960: CRITICAL : stderr: Traceback (most recent call last):
  File "/Users/david/miniconda3/bin/treetime", line 12, in <module>
    return_code = params.func(params)
  File "/Users/david/miniconda3/lib/python3.6/site-packages/treetime/wrappers.py", line 658, in ancestral_reconstruction
    report_ambiguous=params.report_ambiguous)
  File "/Users/david/miniconda3/lib/python3.6/site-packages/treetime/wrappers.py", line 215, in export_sequences_and_tree
    Phylo.write(tt.tree, outtree_name, 'nexus', format_branch_length=fmt_bl)
  File "/Users/david/miniconda3/lib/python3.6/site-packages/Bio/Phylo/_io.py", line 83, in write
    n = getattr(supported_formats[format], "write")(trees, fp, **kwargs)
  File "/Users/david/miniconda3/lib/python3.6/site-packages/Bio/Phylo/NexusIO.py", line 69, in write
    **kwargs))]
  File "/Users/david/miniconda3/lib/python3.6/site-packages/Bio/Phylo/NexusIO.py", line 66, in <listcomp>
    nexus_trees = [TREE_TEMPLATE % {"index": idx + 1, "tree": nwk}
  File "/Users/david/miniconda3/lib/python3.6/site-packages/Bio/Phylo/NewickIO.py", line 289, in to_strings
    rawtree = newickize(tree.root) + ";"
  File "/Users/david/miniconda3/lib/python3.6/site-packages/Bio/Phylo/NewickIO.py", line 281, in newickize
    return "(%s)%s" % (",".join(subtrees),
  File "/Users/david/miniconda3/lib/python3.6/site-packages/Bio/Phylo/NewickIO.py", line 280, in <genexpr>
    subtrees = (newickize(sub) for sub in clade)
  File "/Users/david/miniconda3/lib/python3.6/site-packages/Bio/Phylo/NewickIO.py", line 281, in newickize
    return "(%s)%s" % (",".join(subtrees),
  File "/Users/david/miniconda3/lib/python3.6/site-packages/Bio/Phylo/NewickIO.py", line 280, in <genexpr>
```
... repetitive bit edited out

```
 File "/Users/david/miniconda3/lib/python3.6/site-packages/Bio/Phylo/NewickIO.py", line 281, in newickize
    return "(%s)%s" % (",".join(subtrees),
  File "/Users/david/miniconda3/lib/python3.6/site-packages/Bio/Phylo/NewickIO.py", line 280, in <genexpr>
    subtrees = (newickize(sub) for sub in clade)
  File "/Users/david/miniconda3/lib/python3.6/site-packages/Bio/Phylo/NewickIO.py", line 272, in newickize
    unquoted_label = re.match(token_dict["unquoted node label"], label)
  File "/Users/david/miniconda3/lib/python3.6/re.py", line 172, in match
    return _compile(pattern, flags).match(string)
RecursionError: maximum recursion depth exceeded
```

**Comment by rneher** [comment]
yes, this is likely a very large very unbalanced tree. you can increase the maximal recursion depth using

`sys.setrecursionlimit(10000)`

**Comment by antoine4ucsd** [comment]
it seems like it could help me. how can it be adapted when using from the terminal cmd line (conda installation)
thank you

**Comment by antoine4ucsd** [comment]
I am closing it. problem fixed when adding sys.setrecursionlimit(10000) to the treetime file (in the conda env)
Thank you!
