### ISSUE TITLE
MissingDataError

### ISSUE THREAD

**Issue by tasbd4** [neherlab/treetime#125]
Attempting to parse dates...
	Using column 'name' as name. This needs match the taxon names in the tree!!
	Using column 'date' as date.

0.00	-TreeAnc: set-up
Traceback (most recent call last):
  File "/home/d3w/miniconda3/envs/tree/bin/treetime", line 12, in <module>
    return_code = params.func(params)
  File "/home/d3w/miniconda3/envs/tree/lib/python3.8/site-packages/treetime/argument_parser.py", line 213, in toplevel
    timetree(params)
  File "/home/d3w/miniconda3/envs/tree/lib/python3.8/site-packages/treetime/wrappers.py", line 516, in timetree
    myTree = TreeTime(dates=dates, tree=params.tree, ref=ref,
  File "/home/d3w/miniconda3/envs/tree/lib/python3.8/site-packages/treetime/treetime.py", line 34, in __init__
    super(TreeTime, self).__init__(*args, **kwargs)
  File "/home/d3w/miniconda3/envs/tree/lib/python3.8/site-packages/treetime/clock_tree.py", line 83, in __init__
    self._assign_dates()
  File "/home/d3w/miniconda3/envs/tree/lib/python3.8/site-packages/treetime/clock_tree.py", line 130, in _assign_dates
    raise MissingDataError("ERROR: ALMOST NO VALID DATE CONSTRAINTS")
treetime.MissingDataError: ERROR: ALMOST NO VALID DATE CONSTRAINTS

name	date
NC_045512.2	2019-12-29
EPI_ISL_402120	2020-01-22
EPI_ISL_402121	2020-01-25
EPI_ISL_402124	2020-02-28
EPI_ISL_404253	2020-02-28
EPI_ISL_404895	2020-03-28
EPI_ISL_406034	2020-04-02
EPI_ISL_406036	2020-05-01
EPI_ISL_406716	2020-02-24
EPI_ISL_406717	2020-01-28
EPI_ISL_406862	2020-02-05
EPI_ISL_407071	2020-02-29
EPI_ISL_407073	2020-03-31
EPI_ISL_407214	2020-04-01
EPI_ISL_407215	2020-01-25
EPI_ISL_407894	2020-02-08
EPI_ISL_408430	2020-04-13
EPI_ISL_408487	2020-01-31
EPI_ISL_408670	2020-04-10

This is the metadata format. working with COVID19 sequences from GISAID. maybe dates are too close that's why? what is the solution then? 

Thank you

**Comment by rneher** [comment]
the format looks fine, assuming the whitespace is tabs. What are the names of your sequences and tips in the tree? also accession numbers?
