### ISSUE TITLE
treetime tool error: zero-size array to reduction operation minimum which has no identity

### ISSUE THREAD

**Issue by ayoraind** [neherlab/treetime#130]
Dear Colleague,

I encountered an error while trying to run the command on my local PC:

treetime --aln aligned_pseudogenome.fas --tree Kleb_pneumo_tree_with_tip_labels.nwk --dates tree_date_for_R.csv

The error is carefully stated below:

4471.86	###TreeTime.run: INITIAL ROUND
/Users/ghru/anaconda3/lib/python3.7/site-packages/treetime/branch_len_interpolator.py:75: RuntimeWarning: invalid value encountered in double_scalars
  sigma_sq = p0*(nm_inv-1)*(nm_inv - p0*(nm_inv-1))*one_mutation
/Users/ghru/anaconda3/lib/python3.7/site-packages/treetime/branch_len_interpolator.py:75: RuntimeWarning: overflow encountered in double_scalars
  sigma_sq = p0*(nm_inv-1)*(nm_inv - p0*(nm_inv-1))*one_mutation
Traceback (most recent call last):
  File "/Users/ghru/anaconda3/bin/treetime", line 12, in <module>
    return_code = params.func(params)
  File "/Users/ghru/anaconda3/lib/python3.7/site-packages/treetime/argument_parser.py", line 213, in toplevel
    timetree(params)
  File "/Users/ghru/anaconda3/lib/python3.7/site-packages/treetime/wrappers.py", line 566, in timetree
    use_covariation = params.covariation, n_points=params.n_skyline)
  File "/Users/ghru/anaconda3/lib/python3.7/site-packages/treetime/treetime.py", line 178, in run
    self.make_time_tree(**tt_kwargs)
  File "/Users/ghru/anaconda3/lib/python3.7/site-packages/treetime/clock_tree.py", line 345, in make_time_tree
    self._ml_t_joint()
  File "/Users/ghru/anaconda3/lib/python3.7/site-packages/treetime/clock_tree.py", line 407, in _ml_t_joint
    subtree_distribution = Distribution.multiply(msgs_to_multiply)
  File "/Users/ghru/anaconda3/lib/python3.7/site-packages/treetime/distribution.py", line 102, in multiply
    peak = y_vals.min()
  File "/Users/ghru/anaconda3/lib/python3.7/site-packages/numpy/core/_methods.py", line 32, in _amin
    return umr_minimum(a, axis, None, out, keepdims, initial)
ValueError: zero-size array to reduction operation minimum which has no identity

As this is the first time I am using this tool, I do not understand this error. Could you kindly explain to me what I did wrong and how this could be corrected? 

Thank you.

**Comment by rneher** [comment]
Thanks for posting. Could give the exact version or commit you are using? This looks like a numerical problem. What kind of data are you using? is this a SNPs only alignment? How good is the clock signal?

**Comment by ayoraind** [comment]
Dear Richard Neher,
Many thanks for your reply. I am using treetime 0.7.6. I am working on WGS data. This is a SNPs only alignment. 
The results from the clock signal are as follows.
Root-Tip-Regression:
 --rate:	3.073e+02
 --r^2:  	0.00

--- root-date:	 1892.23

The graph does not appear to show any form of regression. 
<img width="896" alt="Screenshot 2020-08-30 at 16 54 59" src="https://user-images.githubusercontent.com/43066737/91663953-d299ec00-eae3-11ea-831b-8fa2bd304b76.png">

**Comment by rneher** [comment]
the problem here is going to be the unit of branch length. How did you reconstruct the tree? It seems your root-to-tip distance is 10s of thousands. is this just the number of SNPs? There also is no clock signal. so a time tree is unlikely to be sensible.

**Comment by ayoraind** [comment]
You are right. The major issue was the unit of branch length. I initially rescaled the tree. Now, I used the original tree and the problem is almost solved as a result. I also noted that I have to remove the reference genome tree node from the tree, since the corresponding alignment file for the reference genome was absent. Although I was able to generate the timetree.pdf file, I encountered an error just before the end of the analysis, which is different from the error I initially reported.

I used the command:

treetime --aln aligned_pseudogenome.fas --tree Klebsiella_pneumoniae.nexus --dates tree_date_for_R.csv

I encountered this error:

Traceback (most recent call last):
  File "/Users/ghru/anaconda3/bin/treetime", line 12, in <module>
    return_code = params.func(params)
  File "/Users/ghru/anaconda3/lib/python3.7/site-packages/treetime/argument_parser.py", line 213, in toplevel
    timetree(params)
  File "/Users/ghru/anaconda3/lib/python3.7/site-packages/treetime/wrappers.py", line 626, in timetree
    reconstruct_tip_states=params.reconstruct_tip_states)
  File "/Users/ghru/anaconda3/lib/python3.7/site-packages/treetime/wrappers.py", line 176, in export_sequences_and_tree
    AlignIO.write(tt.get_reconstructed_alignment(reconstruct_tip_states=reconstruct_tip_states), outaln_name, 'fasta')
  File "/Users/ghru/anaconda3/lib/python3.7/site-packages/treetime/treeanc.py", line 1572, in get_reconstructed_alignment
    for n in self.tree.find_clades()])
  File "/Users/ghru/anaconda3/lib/python3.7/site-packages/treetime/treeanc.py", line 1572, in <listcomp>
    for n in self.tree.find_clades()])
  File "/Users/ghru/anaconda3/lib/python3.7/site-packages/treetime/treeanc.py", line 1616, in sequence
    tmp_seq = self.data.compressed_to_full_sequence(node.cseq, as_string=False)
  File "/Users/ghru/anaconda3/lib/python3.7/site-packages/treetime/sequence_data.py", line 485, in compressed_to_full_sequence
    tmp_seq = sequence[self.full_to_compressed_sequence_map[:L]]
TypeError: 'NoneType' object is not subscriptable

Is there a way to avoid this error?

**Comment by rneher** [comment]
thanks. this looks like a bug. It either is a missing sequence, or something odd is happing in the export step. Would be great if you could send me the data to trouble shoot (via email for example).

**Comment by rneher** [comment]
I think this is due to missing input (for example mismatch between sequence and taxon names). This should have been caught, but wasn't. 

hopefully fixed in https://github.com/neherlab/treetime/commit/7525775c1440d5dcf5a38cb58868a8c3fd87c89b
