### ISSUE TITLE
treetime.MissingDataError: ERROR: ALMOST NO VALID DATE CONSTRAINTS

### ISSUE THREAD

**Issue by safinaARK** [neherlab/treetime#140]
I have read the similiar issue reported and i have already applied the fixes taht were suggested in that but still getting the error:
My command:
`augur refine --tree ../results/tree_raw.nwk --alignment ../results/aligned.fasta --metadata uk_strains_metadata_crctd_strns.tsv --output-tree ../results/tree.nwk --output-node-data ../results/branch_lengths.json --timetree --coalescent opt --date-confidence --date-inference marginal `

My files attached:
[uk_strains.zip](https://github.com/neherlab/treetime/files/5795268/uk_strains.zip)

Error:
`augur refine is using TreeTime version 0.8.1
Traceback (most recent call last):
  File "../augur/bin/./augur", line 24, in <module>
    exit( main() )
  File "../augur/augur/__main__.py", line 10, in main
    return augur.run( argv[1:] )
  File "../augur/augur/__init__.py", line 74, in run
    return args.__command__.run(args)
  File "../augur/augur/refine.py", line 206, in run
    tt = refine(tree=T, aln=aln, ref=ref, dates=dates, confidence=args.date_confidence,
  File "../augur/augur/refine.py", line 36, in refine
    tt = TreeTime(tree=tree, aln=aln, ref=ref, dates=dates,
  File "/home/workshop/.local/lib/python3.8/site-packages/treetime/treetime.py", line 34, in __init__
    super(TreeTime, self).__init__(*args, **kwargs)
  File "/home/workshop/.local/lib/python3.8/site-packages/treetime/clock_tree.py", line 83, in __init__
    self._assign_dates()
  File "/home/workshop/.local/lib/python3.8/site-packages/treetime/clock_tree.py", line 130, in _assign_dates
    raise MissingDataError("ERROR: ALMOST NO VALID DATE CONSTRAINTS")
treetime.MissingDataError: ERROR: ALMOST NO VALID DATE CONSTRAINTS`

**Comment by rneher** [comment]
The metadata and alignment look fine. But please check that the taxon names in the tree match the strain names in the table and the alignment.
