### ISSUE TITLE
ValueError: zero-size array to reduction operation minimum which has no identity

### ISSUE THREAD

**Issue by stitam** [neherlab/treetime#171]
Many thanks for developing this tool!

I am currently receiving the following error message:

`ValueError: zero-size array to reduction operation minimum which has no identity`

I looked at the related issue #130 but could not fix it on my end. My workflow summary: 150 bacterial genomes -> predict SNPs -> mask recombination sites and calculate tree topology -> run treetime 

This is my traceback:

```
1.22    ###TreeTime.run: INITIAL ROUND
Traceback (most recent call last):
  File "/home/myname/.local/bin/treetime", line 12, in <module>
    return_code = params.func(params)
  File "/home/myname/.local/lib/python3.9/site-packages/treetime/argument_parser.py", line 213, in toplevel
    timetree(params)
  File "/home/myname/.local/lib/python3.9/site-packages/treetime/wrappers.py", line 556, in timetree
    success = myTree.run(root=root, relaxed_clock=relaxed_clock_params,
  File "/home/myname/.local/lib/python3.9/site-packages/treetime/treetime.py", line 178, in run
    self.make_time_tree(**tt_kwargs)
  File "/home/myname/.local/lib/python3.9/site-packages/treetime/clock_tree.py", line 345, in make_time_tree
    self._ml_t_joint()
  File "/home/myname/.local/lib/python3.9/site-packages/treetime/clock_tree.py", line 407, in _ml_t_joint
    subtree_distribution = Distribution.multiply(msgs_to_multiply)
  File "/home/myname/.local/lib/python3.9/site-packages/treetime/distribution.py", line 103, in multiply
    peak = y_vals.min()
  File "/usr/lib/python3/dist-packages/numpy/core/_methods.py", line 43, in _amin
    return umr_minimum(a, axis, None, out, keepdims, initial, where)
ValueError: zero-size array to reduction operation minimum which has no identity
```
Used treetime v0.8.5, default settings.

* After masking recombination sites my sequences include the 4 nucleotides, `-` for gaps and `N` for masked sites.
* Treetime worked well when I ran it with a subset of 20 genomes but in that run there much fewer masked sites and I didn't have gaps in the final alignment.

Any help with this issue would be highly appreciated.

**Comment by rneher** [comment]
Hi @stitam 
thanks for reporting this. This is probably some issue with super long or very short branches that are not correctly handled. If it is possible for you to share your alignment/tree that would help to identify the problem.

best,
richard
