### ISSUE TITLE
ERROR: local variable 'peak' referenced before assignment

### ISSUE THREAD

**Issue by joverlee521** [neherlab/treetime#233]
Seeing this error from `augur refine` in our private seasonal flu builds:
```
[batch] [2023-04-20T15:51:14-07:00] Traceback (most recent call last):
[batch] [2023-04-20T15:51:14-07:00]   File "/usr/local/lib/python3.10/site-packages/treetime/treetime.py", line 57, in run
[batch] [2023-04-20T15:51:14-07:00]     return self._run(**kwargs)
[batch] [2023-04-20T15:51:14-07:00]   File "/usr/local/lib/python3.10/site-packages/treetime/treetime.py", line 329, in _run
[batch] [2023-04-20T15:51:14-07:00]     self.calc_rate_susceptibility(rate_std=vary_rate, params=tt_kwargs)
[batch] [2023-04-20T15:51:14-07:00]   File "/usr/local/lib/python3.10/site-packages/treetime/clock_tree.py", line 872, in calc_rate_susceptibility
[batch] [2023-04-20T15:51:14-07:00]     self.make_time_tree(**params)
[batch] [2023-04-20T15:51:14-07:00]   File "/usr/local/lib/python3.10/site-packages/treetime/clock_tree.py", line 378, in make_time_tree
[batch] [2023-04-20T15:51:14-07:00]     self._ml_t_marginal()
[batch] [2023-04-20T15:51:14-07:00]   File "/usr/local/lib/python3.10/site-packages/treetime/clock_tree.py", line 744, in _ml_t_marginal
[batch] [2023-04-20T15:51:14-07:00]     node.marginal_pos_LH = NodeInterpolator.multiply((node.msg_from_parent, node.subtree_distribution))
[batch] [2023-04-20T15:51:14-07:00]   File "/usr/local/lib/python3.10/site-packages/treetime/distribution.py", line 121, in multiply
[batch] [2023-04-20T15:51:14-07:00]     ind = (y_vals-peak)<BIG_NUMBER/1000
[batch] [2023-04-20T15:51:14-07:00] UnboundLocalError: local variable 'peak' referenced before assignment
[batch] [2023-04-20T15:51:14-07:00] ERROR: local variable 'peak' referenced before assignment
[batch] [2023-04-20T15:51:14-07:00]
[batch] [2023-04-20T15:51:14-07:00] ERROR in TreeTime.run: An error occurred which was not properly handled in TreeTime. If this error persists, please let us know by filing a new issue including the original command and the error above at: https://github.com/neherlab/treetime/issues
[batch] [2023-04-20T15:51:14-07:00] ERROR from TreeTime: An error occurred in TreeTime (see above). This may be due to an issue with TreeTime or Augur.
[batch] [2023-04-20T15:51:14-07:00] Please report you are calling TreeTime via Augur.
[batch] [2023-04-20T15:51:14-07:00] augur refine is using TreeTime version 0.9.6
```

**Comment by joverlee521** [comment]
I was able to rerun the build without error using an older Docker image (`nextstrain/base:build-20230411T103027Z`) that uses TreeTime version 0.9.5

**Comment by rneher** [comment]
thanks, Jover! I ran into this as well. 

the proximal cause it that errors that were supposed to be raised weren't. But the real reason is a pileup of numerical issues that stem from the enormous caterpillar trees in these flu trees. This error doesn't arise when one doesn't resolve polytomies or resolves them using the new stochastic resolve. 

I'll think about how to fix this -- but the short term solutions are 
 * role back to 0.9.5 (where this problem was papered over in a way that mostly worked)
 * skip polytomy resolution
 * move to stochastic resolution once augur is released with https://github.com/nextstrain/augur/pull/1203

**Comment by huddlej** [comment]
+1 for skipping polytomy resolution with `--keep-polytomies`, especially since this is the direction we want to move to support TreeKnit soon.

**Comment by rneher** [comment]
in commit [40def7](https://github.com/neherlab/treetime/commit/40def7f3e1b3761ba38f1bf151ce25a83e6f9fdf) this is "fixed" in that the previous error is actually raised. But the underlying problem is of numerical nature related to very large polytomy that get resolved in a very lopsided way.
