### ISSUE TITLE
Error running Ancestral Reconstruction

### ISSUE THREAD

**Issue by jrotieno** [neherlab/treetime#40]
I am getting the error below when running treetime. Could it be my conda python?

`File "/Users/jotieno/miniconda2/bin/ancestral_reconstruction.py", line 4, in <module>
    __import__('pkg_resources').run_script('treetime==0.2.4', 'ancestral_reconstruction.py')
  File "/Users/jotieno/miniconda2/lib/python2.7/site-packages/pkg_resources/__init__.py", line 658, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/Users/jotieno/miniconda2/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1445, in run_script
    exec(script_code, namespace, namespace)
  File "/Users/jotieno/miniconda2/lib/python2.7/site-packages/treetime-0.2.4-py2.7.egg/EGG-INFO/scripts/ancestral_reconstruction.py", line 4, in <module>
    __import__('pkg_resources').run_script('treetime==0.2.4', 'ancestral_reconstruction.py')
  File "build/bdist.macosx-10.6-x86_64/egg/treetime/__init__.py", line 2, in <module>
  File "build/bdist.macosx-10.6-x86_64/egg/treetime/treetime.py", line 2, in <module>
  File "build/bdist.macosx-10.6-x86_64/egg/treetime/clock_tree.py", line 1, in <module>
  File "build/bdist.macosx-10.6-x86_64/egg/treetime/utils.py", line 3, in <module>
  File "/usr/local/lib/python2.7/site-packages/scipy/__init__.py", line 118, in <module>
  File "/usr/local/lib/python2.7/site-packages/scipy/_lib/_ccallback.py", line 1, in <module>
ImportError: cannot import name _ccallback_c`

**Comment by rneher** [comment]
this looks as if something is wrong with your scipy installation. what version of scipy are you using? does `import scipy` work?

**Comment by jrotieno** [comment]
@rneher 
You were absolutely right.  I am using a conda python 2.7 with scipy installed in `/Users/jotieno/miniconda2/lib/python2.7/site-packages,`  there was a previous scipy installed in 
`/usr/local/lib/python2.7/site-packages/` that I was causing the problem. Removed that and all is running well.

Thanks a lot!

**Comment by idolawoye** [comment]
Hi Richard,
I installed treetime but when I tried running it I encountered an error which can be found below:
  ```   
0.00    -TreeAnc: set-up

0.06    -TreeAnc: loading alignment failed...

0.06    -TreeAnc.infer_ancestral_sequences: method: ml

0.06    -TreeAnc inferring the GTR model from the tree...
Traceback (most recent call last):
  File "C:/Users/Idowu/AppData/Local/Programs/Python/Python36/Scripts/ancestral_reconstruction.py", line 4, in <module>
    __import__('pkg_resources').run_script('treetime==0.4.1', 'ancestral_reconstruction.py')
  File "C:\Users\Idowu\AppData\Local\Programs\Python\Python36\lib\site-packages\pkg_resources\__init__.py", line 658, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "C:\Users\Idowu\AppData\Local\Programs\Python\Python36\lib\site-packages\pkg_resources\__init__.py", line 1445, in run_script
    exec(script_code, namespace, namespace)
  File "c:\users\idowu\appdata\local\programs\python\python36\lib\site-packages\treetime-0.4.1-py3.6.egg\EGG-INFO\scripts\ancestral_reconstruction.py", line 92, in <module>
  File "c:\users\idowu\appdata\local\programs\python\python36\lib\site-packages\treetime-0.4.1-py3.6.egg\treetime\treeanc.py", line 719, in infer_ancestral_sequences
  File "c:\users\idowu\appdata\local\programs\python\python36\lib\site-packages\treetime-0.4.1-py3.6.egg\treetime\treeanc.py", line 759, in reconstruct_anc
  File "c:\users\idowu\appdata\local\programs\python\python36\lib\site-packages\treetime-0.4.1-py3.6.egg\treetime\treeanc.py", line 680, in infer_gtr
  File "c:\users\idowu\appdata\local\programs\python\python36\lib\site-packages\treetime-0.4.1-py3.6.egg\treetime\treeanc.py", line 1248, in _ml_anc_joint
AttributeError: 'TreeAnc' object has no attribute 'multiplicity'
```
Can you kindly help out? Thanks
