### ISSUE TITLE
treetime clock fails (partially)

### ISSUE THREAD

**Issue by phiweger** [neherlab/treetime#60]
```bash
treetime clock --tree core.nwk --aln core.aln --dates dates.csv --reroot least-squares

0.00	-TreeAnc: set-up
The following leaves don't follow a loose clock and will be ignored in rate estimation:
	A
	B
	C
	D

 Root-Tip-Regression:
 --rate:	1.074e-02
 --r^2:  	0.49

The R^2 value indicates the fraction of variation in
root-to-tip distance explained by the sampling times.
Higher values corresponds more clock-like behavior (max 1.0).

The rate is the slope of the best fit of the date to
the root-to-tip distance and provides an estimate of
the substitution rate. The rate needs to be positive!
Negative rates suggest an inappropriate root.


The estimated rate and tree correspond to a root date:

--- root-date:	 1998.44


--- re-rooted tree written to
	2018-08-24_clock/rerooted.newick

Traceback (most recent call last):
  File ".../bin/treetime", line 264, in <module>
    return_code = params.func(params)
  File ".../lib/python3.6/site-packages/treetime/wrappers.py", line 813, in estimate_clock_model
    ofile.write("%s, %f, %f\n"%(n.name, n.raw_date_constraint, n.dist2root))
TypeError: must be real number, not list
```

**Comment by rneher** [comment]
I merged this into master now. let us know if you have more issues.
